#Docker compose file is to map between two containers

version: '3'
services: 
  redis-server:
    image: 'redis'
  node-app:
    restart: always #restart policy. There are 3 more
    build: .
    ports: 
      - "4001:8081" #http://localhost:4001/  